server {
    listen 80 default_server;
    listen [::]:80 default_server;

    server_name localhost;

    root /home/USERNAME/public_html;
    index index.php index.html index.htm;

    client_max_body_size 10G;
    client_body_timeout 7200s;
    fastcgi_buffers 64 4K;


    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        try_files $uri =404;
        include fastcgi_params;
        fastcgi_pass unix:/run/php/php8.5-fpm.sock;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_connect_timeout 300s;
        fastcgi_send_timeout 300s;
        fastcgi_read_timeout 300s;



    }

    location ~ /\. {
        deny all;
    }
}
